#!/bin/sh

# Copyright (C) 2016 Jak Wings https://github.com/jakwings/totp
#
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

# Better than nothing: http://www.in-ulm.de/~mascheck/various/set-e/
set -euf +x

# copy-able text should go to fd 3
exec 3>&1 1>&2

export LC_ALL=C
unset IFS  # also unexport

EOL='
'

help() {
  printf '%s' 'totp -- Time-based One-time Password Generator

USAGE: totp [server] [interval] [timestamp] < secret

The default update interval is 30 seconds.
Timestamp is the seconds since 1970-01-01 00:00:00 UTC.

Supported servers: Google, GitHub, GitLab, Bitbucket
'
}

echo() {
  printf '%s\n' "$*"
}
ekho() {
  printf '\n[Error] %s\n' "$*"
}
die() {
  if [ 0 -lt "$#" ]; then ekho "$@" >&2; fi
  exit 1
}

hex2bin() {
  while [ 0 -lt "${#1}" ]; do
    case "$1" in
      ([0-9A-Fa-f][0-9A-Fa-f]*)
        set -- "${1#??}" "$1"
        printf "\\$(printf '%03o' "$(( 0x${2%"$1"} ))")"
        ;;
      (*) set -- "${1#?}"
    esac
  done
}

# https://datatracker.ietf.org/doc/html/rfc4648
base32decode2hex() (
  alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
  input="$(printf '%s' $*)"
  [ 0 -ne "${#input}" ] || return 0
  [ 0 -eq "$(( ${#input} % 8 ))" ] || die 'base32: invalid input'
  case "${input}" in (*[!"${alphabet}"=]*) die 'base32: invalid input'; esac
  input="${input%%=*}" bite=0 bits=0
  while [ 0 -lt "${#input}" ]; do
    s="${alphabet%%"${input%"${input#?}"}"*}"
    i="${#s}"
    bite="$(( (bite << 5) | i ))"
    bits="$(( bits + 5 ))"
    if [ 8 -le "${bits}" ]; then
      byte="$(( bite >> (bits - 8) ))"
      printf '%02x' "${byte}"
      bite="$(( bite - (byte << (bits - 8)) ))"
      bits="$(( bits - 8 ))"
    fi
    input="${input#?}"
  done
)

gen_digest() (
  set -e
  key="$1"
  period="$(printf '%016X' "$2")"
  digest="$(
    set -e
    # NUL is considered harmful. Avoid -hmac <binarykey>!
    hh="${key}"
    while [ 0 -lt "${#hh}" ]; do
      case "${hh}" in (00*) break; esac
      hh="${hh#??}"
    done
    # FIXME: can we not put the key on argv?
    if [ 0 -ne "${#hh}" ]; then
      hex2bin "${period}" | openssl dgst -sha1 -mac hmac -macopt "hexkey:${key}"
    else  # hexkey not supported by old versions from BSD/OSX!
      key="$(hex2bin "${key}" && printf x)"
      hex2bin "${period}" | openssl dgst -sha1 -hmac "${key%x}"
    fi
  )"
  echo "${digest##*' '}"
)

# https://datatracker.ietf.org/doc/html/rfc6238
#{
  case "${1-}" in (help|-h*|--help|--help=*|-\?*)
    help >&3; exit 0
  esac

  server="${1-Google}"
  interval="${2-30}"
  now="${3-"$(date '+%s')"}"

  if [ -t 0 ]; then
    echo "Enter your secret token: (Press Ctrl-D once/twice to Quit)"
  fi
  secret="$(cat)"

  err=''
  if [ '' = "${secret}" ]; then
    err="${err}${EOL}The secret token was empty!"
  fi
  if [ 0 -ge "${interval}" ]; then
    err="${err}${EOL}interval was not a valid positive integer: \"${interval}\""
  fi
  if ! { [ 0 -le "${now}" ] || [ 0 -ge "${now}" ]; } 2>/dev/null; then
    err="${err}${EOL}timestamp was not a valid integer: \"${now}\""
  fi
  if [ 0 -lt "${#err}" ]; then
    help
    IFS="${EOL}"
    for msg in $err; do ekho "${msg}"; done
    die
  fi

  # remove whitespace and leading zeros and number sign
  interval="$(( ${interval#"${interval%%[1-9]*}"} + 0 ))"

  # remove whitespace and leading zeros while preserving signness
  now="$(( ${now%%[0-9]*}${now#"${now%%[1-9]*}"} + 0 ))"

  period="$(( now / interval ))"

  case "${server}" in
    # https://github.com/google/google-authenticator/wiki/Key-Uri-Format
    ([gG][oO][oO][gG][lL][eE]\
    |[gG][iI][tT][hH][uU][bB]\
    |[gG][iI][tT][lL][aA][bB]\
    |[bB][iI][tT][bB][uU][cC][kK][eE][tT]\
    )
      key="$(base32decode2hex "${secret}")"
      [ 0 -lt "${#key}" ] || exit 2
      # The digest is a 160-bit hexadecimal number string.
      digest="$(gen_digest "${key}" "${period}")"
      [ 40 -eq "${#digest}" ] || exit 3
      # Read the last 4 bits and convert it into an unsigned integer.
      offset="$(( 0x${digest#"${digest%?}"} * 2 ))"
      [ 33 -ge "${offset}" ] || exit 4
      # Read a 32-bit positive integer and take at most six rightmost digits.
      nibble="$(printf "%.${offset}s" "${digest}")"
      number="0x$(printf '%.8s' "${digest#"${nibble}"}")"
      token="$(( (number & 0x7FFFFFFF) % 1000000 ))"
      # Pad the token number with leading zeros if needed.
      printf '%06d\n' "${token}" >&3
      ;;
    (*)
      help
      die "Your server is not supported: \"${server}\""
  esac
#}
